[profile.default]
src = "contracts/src"
out = "contracts/out"
libs = ["contracts/lib"]
solc_version = "0.8.20"
optimizer = true
optimizer_runs = 200
via_ir = false

[profile.default.metadata]
bytecode_hash = "ipfs"

[rpc_endpoints]
polygon = "https://polygon-rpc.com"
mumbai = "https://rpc-mumbai.maticvigil.com"
localhost = "http://127.0.0.1:8545"

[etherscan]
polygon = { key = "${POLYGONSCAN_API_KEY}" }
mumbai = { key = "${POLYGONSCAN_API_KEY}" }

